//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTT.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSTEmployee()
        {
            this.TSTMails = new HashSet<TSTMail>();
            this.TSTMails1 = new HashSet<TSTMail>();
            this.TSTTechNotes = new HashSet<TSTTechNote>();
            this.TSTTickets = new HashSet<TSTTicket>();
            this.TSTTickets1 = new HashSet<TSTTicket>();
        }
    
        public int EmployeeID { get; set; }
        public string UserID { get; set; }
        public int EmpStatusID { get; set; }
        public string EmpImage { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string JobTitle { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string StreetAddress { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Email { get; set; }
        public string CellPhone { get; set; }
        public System.DateTime DateOfHire { get; set; }
        public Nullable<System.DateTime> DateOfSeparation { get; set; }
        public string EmpNotes { get; set; }
    
        public virtual TSTDepartment TSTDepartment { get; set; }
        public virtual TSTEmpStatus TSTEmpStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTMail> TSTMails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTMail> TSTMails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTTechNote> TSTTechNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTTicket> TSTTickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTTicket> TSTTickets1 { get; set; }
    }
}
