//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTT.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTMail
    {
        public int MailID { get; set; }
        public string MailSubject { get; set; }
        public string MailMessage { get; set; }
        public int SentByID { get; set; }
        public System.DateTime DateSent { get; set; }
        public int PriorityID { get; set; }
        public int RecipientID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TSTEmployee TSTEmployee { get; set; }
        public virtual TSTEmployee TSTEmployee1 { get; set; }
        public virtual TSTPriority TSTPriority { get; set; }
    }
}
