//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTT.DATA.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TSTEntities : DbContext
    {
        public TSTEntities()
            : base("name=TSTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TSTDepartment> TSTDepartments { get; set; }
        public virtual DbSet<TSTEmployee> TSTEmployees { get; set; }
        public virtual DbSet<TSTEmpStatus> TSTEmpStatuses { get; set; }
        public virtual DbSet<TSTMail> TSTMails { get; set; }
        public virtual DbSet<TSTPriority> TSTPriorities { get; set; }
        public virtual DbSet<TSTTechNote> TSTTechNotes { get; set; }
        public virtual DbSet<TSTTicket> TSTTickets { get; set; }
        public virtual DbSet<TSTTicketStatus> TSTTicketStatuses { get; set; }
    }
}
